// watchlist builder — the interpretation stage: facts × lens → judgments.
//
// Reads each wiki page's neutral Evaluation scores and applies profile/lens.md
// (via lib/lens) to assign a signal (adopt / trial / watch / hold / deprecated).
// This is the ONLY place judgments are formed, and it is fully re-runnable when
// the lens changes — no re-ingest.
//
// Outputs:
//   docs/watchlist.json                     — structured judgments for agents
//   docs/wiki/recommendations-watchlist.md  — human-readable page

const fs = require('fs');
const path = require('path');
const { ROOT } = require('../../../scripts/lib/manifest');
const { loadPages } = require('../../../scripts/lib/wiki');
const { loadLens, judge } = require('../../../scripts/lib/lens');

const DOCS = path.join(ROOT, 'docs');
const SIGNAL_ORDER = ['adopt', 'trial', 'watch', 'hold', 'deprecated', 'unscored'];
const SIGNAL_LABEL = {
  adopt: 'Adopt', trial: 'Trial', watch: 'Watch',
  hold: 'Hold', deprecated: 'Deprecated', unscored: 'Unscored',
};

function today() {
  return new Date().toISOString().slice(0, 10);
}

async function build() {
  const lens = loadLens();
  const pages = loadPages().filter(p => !p.generated);
  const written = [];

  const items = pages.map(p => {
    const verdict = judge(p.scores, lens, { tags: p.tags });
    return {
      title: p.title, slug: p.slug, path: p.file, tags: p.tags,
      scores: p.scores || null,
      signal: verdict.signal, score: verdict.score, reason: verdict.reason,
    };
  });

  const bySignal = {};
  for (const it of items) (bySignal[it.signal] ||= []).push(it);

  const watchlist = {
    generated: new Date().toISOString(),
    lens: lens.stance,
    weights: lens.weights,
    counts: Object.fromEntries(SIGNAL_ORDER.map(s => [s, (bySignal[s] || []).length])),
    items,
  };
  const jsonPath = path.join(DOCS, 'watchlist.json');
  fs.writeFileSync(jsonPath, JSON.stringify(watchlist, null, 2) + '\n');
  written.push(path.relative(ROOT, jsonPath));

  const scored = items.filter(it => it.signal !== 'unscored');
  const md = [];
  md.push('---');
  md.push('title: Recommendations & Watchlist');
  md.push('tags: [analysis, watchlist]');
  md.push(`created: ${today()}`);
  md.push(`updated: ${today()}`);
  md.push('generated: true');
  md.push('---');
  md.push('');
  md.push('# Recommendations & Watchlist');
  md.push('');
  md.push('## Summary');
  md.push('');
  md.push(`Generated by the interpretation builder from neutral facts seen through the **${lens.stance}** lens (\`profile/lens.md\`). This page is derived — do not edit by hand; re-run \`node scripts/pipeline.js build\` to regenerate. Changing the lens re-scores everything without re-ingesting.`);
  md.push('');
  md.push('> **Facts vs. values:** the dimension scores are neutral facts on each source page. The **signal** below is a values judgment from the current lens, and would differ under a different stance.');
  md.push('');

  if (scored.length === 0) {
    md.push('_No pages carry an `## Evaluation` block yet, so there is nothing to judge. Add neutral dimension scores at ingest (see `profile/rubric.md`) and rebuild._');
    md.push('');
  } else {
    for (const sig of SIGNAL_ORDER) {
      if (sig === 'unscored') continue;
      const group = bySignal[sig];
      if (!group || group.length === 0) continue;
      md.push(`## ${SIGNAL_LABEL[sig]}`);
      md.push('');
      md.push('| Page | Score | Why |');
      md.push('|------|-------|-----|');
      for (const it of group.sort((a, b) => (b.score ?? 0) - (a.score ?? 0))) {
        md.push(`| [${it.title}](${it.path}) | ${it.score ?? '—'} | ${it.reason} |`);
      }
      md.push('');
    }
  }

  const unscored = bySignal.unscored || [];
  if (unscored.length) {
    md.push('## Unscored (no evaluation yet)');
    md.push('');
    for (const it of unscored) md.push(`- [${it.title}](${it.path})`);
    md.push('');
  }

  md.push('## Sources');
  md.push('');
  md.push('- Derived from all pages under `docs/wiki/` via the `watchlist` builder.');
  md.push('- Lens: `profile/lens.md`');
  md.push('');

  const pagePath = path.join(DOCS, 'wiki', 'recommendations-watchlist.md');
  fs.writeFileSync(pagePath, md.join('\n'));
  written.push(path.relative(ROOT, pagePath));

  return { written };
}

module.exports = { name: 'watchlist', kind: 'builder', build };
